### ISSUE TITLE
does not work on m1 mac

### ISSUE THREAD

**Issue by Thinkseal** [BouncingElf10/ASCII-Shader#1]
when I try to use this on my m1 mac in 1.21 with iris it does not work and gives this error

composite.fsh: composite.fsh: ERROR: 0:1: '' :  version '430' is not supported
ERROR: 0:1: '' : syntax error: #version
ERROR: 0:2: '' :  #version required and missing.
ERROR: 0:15: '2' : syntax error: integers in layouts require GLSL 140 or later
this is the log [https://mclo.gs/SnOrMAw](https://mclo.gs/SnOrMAw)

**Comment by BouncingElf10** [comment]
Sorry that you got this error, this seems like a big oversight of mine. I made an update (V1.1) that should hopefully fix your issue. Find them on [Modrinth](https://modrinth.com/shader/ascii-shader/version/1.1) or on [Github](https://github.com/BouncingElf10/ASCII-Shader/releases/tag/1.1). If you encounter any further issues feel free to ask :D

**Comment by Thinkseal** [comment]
Thank you for your time I will test to see if this fixed the issue when I get a chance

**Comment by Thinkseal** [comment]
so I tested and it gives a new error
composite1.fsh: composite1.fsh: ERROR: 0:76: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:94: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:95: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:96: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:97: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:98: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:99: Use of undeclared identifier 'depthLeft'
ERROR: 0:99: Use of undeclared identifier 'depthRight'
ERROR: 0:100: Use of undeclared identifier 'depthUp'
ERROR: 0:100: Use of undeclared identifier 'depthDown'
ERROR: 0:101: Use of undeclared identifier 'edgeH'
ERROR: 0:101: Use of undeclared identifier 'edgeV'
ERROR: 0:102: Use of undeclared identifier 'edge'
ERROR: 0:103: Use of undeclared identifier 'edge'
ERROR: 0:105: Use of undeclared identifier 'edge'
ERROR: 0:159: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:161: Use of undeclared identifier 'texColor'
ERROR: 0:162: Use of undeclared identifier 'tC'
ERROR: 0:162: Use of undeclared identifier 'tC'
ERROR: 0:162: Use of undeclared identifier 'tC'
ERROR: 0:163: Use of undeclared identifier 'colorDepth'
ERROR: 0:164: Use of undeclared identifier 'colorDepth'
ERROR: 0:164: Use of undeclared identifier 'invertedColor'
log: [https://mclo.gs/qDAIWfW](https://mclo.gs/qDAIWfW)

**Comment by Thinkseal** [comment]
I am sorry on the timing on that

**Comment by Thinkseal** [comment]
@BouncingElf10

**Comment by Thinkseal** [comment]
ok I will make a new issue
