### ISSUE TITLE
sadly still does not work on m1 mac

### ISSUE THREAD

**Issue by Thinkseal** [BouncingElf10/ASCII-Shader#2]
so the previous problem that made it so that it would not work on m1 macs has been patched although it was a new problem that makes it so it doesn't work sadly
this is the error it gives
composite1.fsh: composite1.fsh: ERROR: 0:76: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:94: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:95: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:96: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:97: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:98: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:99: Use of undeclared identifier 'depthLeft'
ERROR: 0:99: Use of undeclared identifier 'depthRight'
ERROR: 0:100: Use of undeclared identifier 'depthUp'
ERROR: 0:100: Use of undeclared identifier 'depthDown'
ERROR: 0:101: Use of undeclared identifier 'edgeH'
ERROR: 0:101: Use of undeclared identifier 'edgeV'
ERROR: 0:102: Use of undeclared identifier 'edge'
ERROR: 0:103: Use of undeclared identifier 'edge'
ERROR: 0:105: Use of undeclared identifier 'edge'
ERROR: 0:159: Argument 3 to function 'textureOffset' must be a constant expression
ERROR: 0:161: Use of undeclared identifier 'texColor'
ERROR: 0:162: Use of undeclared identifier 'tC'
ERROR: 0:162: Use of undeclared identifier 'tC'
ERROR: 0:162: Use of undeclared identifier 'tC'
ERROR: 0:163: Use of undeclared identifier 'colorDepth'
ERROR: 0:164: Use of undeclared identifier 'colorDepth'
ERROR: 0:164: Use of undeclared identifier 'invertedColor'
log: [https://mclo.gs/qDAIWfW](https://mclo.gs/qDAIWfW)

**Comment by BouncingElf10** [comment]
Aight I'm sorry your still having an issue, please hang on tight while I try and fix it. I'll give you any updates I can :)

**Comment by Thinkseal** [comment]
no problem I have never made shaders and have heard that macOS does not like working with them

**Comment by BouncingElf10** [comment]
Aight, I've done some research where I've come to the conclusion that macOS is probably the cause of these issues. I don't own a Mac (which makes it harder to recreate the errors/bugs) so I just fixed the errors based off what you sent above. You can check it out in the [beta](https://github.com/BouncingElf10/ASCII-Shader/releases/tag/1.2-beta) and tell me if it works. Thanks a lot for your cooperation :D

**Comment by Thinkseal** [comment]
thank you for your time, most of the errors are gone now but it still gives one error
composite2.fsh: composite2.fsh: ERROR: 0:28: Argument 3 to function 'textureOffset' must be a constant expression
log: [https://mclo.gs/TXJadp4](https://mclo.gs/TXJadp4)
once again, thank you so much for your time

**Comment by BouncingElf10** [comment]
ah shoot I missed one 😅, I really hope you don't mind testing [this](https://github.com/BouncingElf10/ASCII-Shader/releases/tag/1.2-beta2) one out for me. It should've fixed all the bugs you mentioned and hopefully works. Just wanted to say thanks a lot because I need to practice anyways on fixing bugs that other users have :D

**Comment by Thinkseal** [comment]
so it gave the same error and I checked and the file composite3.fsh in the shaderpack and it does not seem to be changed I am assuming this is github not wanting to work so it sadly has not been fixed thank you for your time and patience

**Comment by BouncingElf10** [comment]
Augh that's such a stupid mistake of mine, its just that I cant replicate the errors so I miss a few. I'm sorry for this D: I'm sure [this](https://github.com/BouncingElf10/ASCII-Shader/releases/tag/1.2-beta3) version is going to work 🤞

**Comment by Thinkseal** [comment]
it now seems to be giving new errors once again, thank you for your time and work on this
clouds.fsh: clouds.fsh: ERROR: 0:1: '' :  version '430' is not supported
ERROR: 0:2: '' :  #version required and missing.
ERROR: 0:22: '0' : syntax error: integers in layouts require GLSL 140 or later
logs: [https://mclo.gs/UTX3XC6](https://mclo.gs/UTX3XC6)

**Comment by BouncingElf10** [comment]
ah shoot I always seem to miss one, I confident [this](https://github.com/BouncingElf10/ASCII-Shader/releases/tag/1.2-beta4) one will finally work, I have no idea what could possible go wrong (famous last words XD)

**Comment by Thinkseal** [comment]
From my testing, this works fine with the latest release of sodium and iris although when I tested it on 1.8 with optifine it did not work but that is meh so I will mark as solved
